version: '2.2'
services:
  server: 
    image: node:alpine
    working_dir: /app
    environment:
      - JWTKEY=kUYzCw2m9PAOGaDs5oHasmJYNNKgqxJ+3VK1dNX3zM8kTlu0FKH4cmJKqvhveOiW
      - ADMINKEY=067801ea8215ac074eaec4e956f63618bb2200b7aea227deadffad5dbbaee79452cb5115af8b4300680a0eeb3edc1bd0
      - JWTEXPIRE=1440
    restart: unless-stopped
    ports:
      - "7000:7000"
    command: "./wait-for-mongo.sh"
    depends_on:
      - "mongo"
    links:
      - "mongo:mongo"
    volumes:
      - './server:/app'

  mongo:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - './mongo:/data/db'